# Generated by Django 3.0.8 on 2020-07-27 07:57

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20200718_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='pk', unique=True),
        ),
    ]
