# Generated by Django 3.0.8 on 2020-09-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_auto_20200928_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='symptom',
            field=models.CharField(max_length=2000),
        ),
    ]
